version: 2
jobs:
  build:
    working_directory: ~/creditsafe-ruby
    docker:
      - image: ruby:2.5.0
    steps:
      - checkout
      - restore_cache:
          key: gemfile-{{ checksum "Gemfile" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gemfile-{{ checksum "Gemfile" }}
          paths:
            - "vendor/bundle"
      - run: bundle exec rubocop
      - run: bundle exec rspec --format RspecJunitFormatter
